name: Test

on:
  push:
    branches:
      - master

jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run test on docker-compose
        run: |
          docker-compose -f ./docker-compose.yml up -d --abort-on-container-exit
          docker-compose -f ./docker-compose.yml build 
          go test -tags=e2e -v ./...
        working-directory: ./
