name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - uses: actions/checkout@v2

    - name: Build and run Docker Compose Test
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        docker-compose up -d --build
        go test -tags=e2e -v ./...

    - name: Stop Docker Compose
      run: docker-compose down
