name: Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.19
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Build and run app
      run: go build -o app ./cmd/server/main.go

    - name: start app
      env:
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        DB_DB: postgres
        DB_HOST: localhost:5432
        SSL_MODE: disable
      run: ./app

    - name: Run tests
      run: go test -tags=e2e ./...

